spring:
  profiles:
    active: local
logging:
  level:
    root: debug
---
spring:
  config:
    activate:
      on-profile: local
  sql:
    init:
      mode: always
      schema-locations: classpath*:db/petme3-tables.sql
      data-locations: classpath*:db/petme3-data.sql
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/petme3
    username: petme_admin
    password: dkshk@ghkswkd7
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      show_sql: true
      format_sql: true
      use_sql_comments: true
    database-platform: org.hibernate.dialect.MariaDB106Dialect
---
spring:
  config:
    activate:
      on-profile: docker
  sql:
    init:
      mode: always
      schema-locations: classpath*:db/petme3-tables.sql
      data-locations: classpath*:db/petme3-data.sql
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb:3306/petme3
    username: petme_admin
    password: dkshk@ghkswkd7