spring:
  profiles:
    active: local
logging:
  level:
    root: debug
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/petme
    username: petme_admin
    password: P@ssw0rd
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      show_sql: true
      format_sql: true
      use_sql_comments: true
    database-platform: org.hibernate.dialect.MariaDB106Dialect
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb:3306/petme
    username: petme_admin
    password: P@ssw0rd