version: '3.7'

services:
  mariadb:
    container_name: docker-mariadb
    image: mariadb:10.11.2
    init: true
    user: root
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
      - --sql-mode=
    volumes:
      #- /data/petme3/docker/mariadb/initdb.d:/docker-entrypoint-initdb.d
      - ./data/petme3:/var/lib/mysql
      #- /data/petme3/docker/mariadb/config/my.cnf:/etc/mysql/my.cnf
    ports:
      - 3306:3306
    #env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: dkshk@ghkswkd7
      #MARIADB_ROOT_PASSWORD: dkshk@ghkswkd7
      MYSQL_DATABASE: petme3
      MYSQL_USER: petme_admin
      MYSQL_PASSWORD: dkshk@ghkswkd7
      TZ: Asiz/Seoul

  application:
    container_name: petme-api
    image: ilovecorea/petme-api:1.0-SNAPSHOT
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - mariadb
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"

